# Database Creation and Data Loading

## Objective

This notebook creates the Mutual Fund Analytics SQLite database using the schema.sql file and loads all cleaned datasets into their respective tables.

### Tables Created

Dimension Tables
- dim_fund
- dim_date

Fact Tables
- fact_nav
- fact_transactions
- fact_performance
- fact_aum

### Data Sources

- clean_01_fund_master.csv
- clean_02_nav_history.csv
- clean_03_aum_by_fund_house.csv
- clean_07_scheme_performance.csv
- clean_08_investor_transactions.csv

In [1]:
import sqlite3
import pandas as pd

from pathlib import Path

## Define Paths

In [2]:
DATABASE_FILE = "../data/db/Bluestocks_mf.db"

SCHEMA_FILE = "../sql/schema.sql"

DATA_DIR = Path("../data/processed")

## Create Database Connection

In [3]:
conn = sqlite3.connect(
    DATABASE_FILE
)

cursor = conn.cursor()

print("Database Connected")

Database Connected

## Execute Schema.sql

In [4]:
with open(
    SCHEMA_FILE,
    "r",
    encoding="utf-8"
) as f:

    schema = f.read()

cursor.executescript(schema)

conn.commit()

print("Schema Executed Successfully")

Schema Executed Successfully

## Load Fund Master

In [5]:
dim_fund = pd.read_csv(
    DATA_DIR / "clean_01_fund_master.csv"
)

print(dim_fund.shape)

dim_fund.head()

(40, 15)

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [6]:
dim_fund.to_sql(
    "dim_fund",
    conn,
    if_exists="append",
    index=False
)

print("dim_fund loaded")

dim_fund loaded

## Create Date Dimension

In [7]:
nav = pd.read_csv(
    DATA_DIR / "clean_02_nav_history.csv"
)

nav["date"] = pd.to_datetime(
    nav["date"]
)

date_dim = pd.DataFrame()

date_dim["full_date"] = (
    nav["date"]
    .drop_duplicates()
)

date_dim["date_key"] = (
    date_dim["full_date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

date_dim["year"] = (
    date_dim["full_date"]
    .dt.year
)

date_dim["quarter"] = (
    date_dim["full_date"]
    .dt.quarter
)

date_dim["month"] = (
    date_dim["full_date"]
    .dt.month
)

date_dim["month_name"] = (
    date_dim["full_date"]
    .dt.month_name()
)

date_dim["day"] = (
    date_dim["full_date"]
    .dt.day
)

date_dim.head()

   full_date  date_key  year  quarter  month month_name  day
0 2022-01-03  20220103  2022        1      1    January    3
1 2022-01-04  20220104  2022        1      1    January    4
2 2022-01-05  20220105  2022        1      1    January    5
3 2022-01-06  20220106  2022        1      1    January    6
4 2022-01-07  20220107  2022        1      1    January    7

In [8]:
date_dim.to_sql(
    "dim_date",
    conn,
    if_exists="append",
    index=False
)

print("dim_date loaded")

dim_date loaded

## Load NAV Fact Table

In [9]:
fact_nav = pd.read_csv(
    DATA_DIR / "clean_02_nav_history.csv"
)

fact_nav["date"] = pd.to_datetime(
    fact_nav["date"]
)

fact_nav["date_key"] = (
    fact_nav["date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

fact_nav = fact_nav[
    [
        "amfi_code",
        "date_key",
        "nav"
    ]
]

fact_nav.head()

   amfi_code  date_key       nav
0     100016  20220103  520.4608
1     100016  20220104  515.0971
2     100016  20220105  521.7239
3     100016  20220106  515.7880
4     100016  20220107  515.1639

In [10]:
fact_nav.to_sql(
    "fact_nav",
    conn,
    if_exists="append",
    index=False
)

print("fact_nav loaded")

fact_nav loaded

## Load Transactions

In [11]:
txn = pd.read_csv(
    DATA_DIR / "clean_08_investor_transactions.csv"
)

txn["transaction_date"] = pd.to_datetime(
    txn["transaction_date"]
)

txn["full_date"] = (
    txn["transaction_date"]
)

txn["date_key"] = (
    txn["transaction_date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

txn.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status,full_date,date_key
0,INV003054,2024-01-01,119092,Sip,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified,2024-01-01,20240101
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified,2024-01-01,20240101
2,INV003420,2024-01-01,118636,Sip,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified,2024-01-01,20240101
3,INV003436,2024-01-01,118634,Sip,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending,2024-01-01,20240101
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending,2024-01-01,20240101

In [12]:
txn.to_sql(
    "fact_transactions",
    conn,
    if_exists="append",
    index=False
)

print("fact_transactions loaded")

fact_transactions loaded

## Load Performance Data

In [13]:
performance = pd.read_csv(
    DATA_DIR / "clean_07_scheme_performance.csv"
)

performance.head()

,amfi_code,scheme_name,cagr,sharpe,sortino,max_drawdown,last_nav,updated_at
0,100016,100016,2.64,-0.20,-0.35,-24.73,583.61,2026-06-13 10:34:21.081040
1,100025,100025,4.46,-0.57,-0.94,-4.31,31.88,2026-06-13 10:34:21.085581
2,100033,100033,30.12,1.09,1.83,-16.22,342.01,2026-06-13 10:34:21.089143
3,101206,101206,23.54,1.03,1.80,-11.29,773.29,2026-06-13 10:34:21.092143
4,101207,101207,7.94,0.16,0.28,-35.45,53.98,2026-06-13 10:34:21.094532

In [14]:
performance.to_sql(
    "fact_performance",
    conn,
    if_exists="append",
    index=False
)

print("fact_performance loaded")

fact_performance loaded

## Load AUM Data

In [15]:
aum = pd.read_csv(
    DATA_DIR / "clean_03_aum_by_fund_house.csv"
)

aum["date"] = pd.to_datetime(
    aum["date"]
)

aum["full_date"] = aum["date"]

aum["date_key"] = (
    aum["date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

aum.head()

,date,fund_house,aum_lakh_crore,aum_crore,num_schemes,full_date,date_key
0,2022-03-31,SBI Mutual Fund,6.05,605000,186,2022-03-31,20220331
1,2022-03-31,ICICI Prudential MF,4.65,465000,216,2022-03-31,20220331
2,2022-03-31,HDFC Mutual Fund,4.35,435000,195,2022-03-31,20220331
3,2022-03-31,Nippon India MF,2.70,270000,177,2022-03-31,20220331
4,2022-03-31,Kotak Mahindra MF,2.70,270000,168,2022-03-31,20220331

In [16]:
aum.to_sql(
    "fact_aum",
    conn,
    if_exists="append",
    index=False
)

print("fact_aum loaded")

fact_aum loaded

## Verify Data Loads

In [17]:
tables = [

    "dim_fund",
    "dim_date",
    "fact_nav",
    "fact_transactions",
    "fact_performance",
    "fact_aum"

]

for table in tables:

    count = pd.read_sql(
        f"""
        SELECT COUNT(*)
        AS rows
        FROM {table}
        """,
        conn
    )

    print(
        f"{table}:",
        count.iloc[0,0]
    )

dim_fund: 40
dim_date: 1151
fact_nav: 46006
fact_transactions: 32778
fact_performance: 40
fact_aum: 90

In [19]:
# ==================================================
# CREATE DATA DICTIONARY (.md)
# ==================================================

tables = [

    "dim_fund",
    "dim_date",
    "fact_nav",
    "fact_transactions",
    "fact_performance",
    "fact_aum"

]

markdown = []

markdown.append(
    "# Mutual Fund Analytics Platform - Data Dictionary\n"
)

markdown.append(
    "Automatically generated from SQLite database schema.\n"
)

for table in tables:

    markdown.append(f"\n# {table}\n")

    markdown.append(
        "| Column Name | Data Type |\n"
    )

    markdown.append(
        "|------------|-----------|\n"
    )

    schema = pd.read_sql(
        f"""
        PRAGMA table_info({table})
        """,
        conn
    )

    for _, row in schema.iterrows():

        markdown.append(
            f"| {row['name']} | {row['type']} |\n"
        )

# --------------------------------------------------
# SAVE FILE
# --------------------------------------------------

with open(
    "../reports/data_dictionary.md",
    "w",
    encoding="utf-8"
) as f:

    f.writelines(markdown)

print(
    "data_dictionary.md created successfully"
)

data_dictionary.md created successfully

# Conclusion

The SQLite database was successfully created using schema.sql and populated with all required mutual fund datasets.

The database is now ready for:

- SQL Analytics
- Data Warehousing
- Power BI Integration
- Performance Analysis
- Dashboard Development